version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ez-the-read"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ut3ftrhpih95"
s3_prefix = "eztheread"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
